PREFIX ex: <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <https://dbpedia.org/ontology/>
PREFIX dbr: <https://dbpedia.org/resource/>

  CONSTRUCT {
	?ReviewURI rdf:type schema:Review;
	dbo:Country ?marketplaceCountry;
	schema:ratingValue ?stars;
	
	ex:helpful_votes ?votes;
	schema:ratingCount ?totalVotes;
	schema:headline ?headline;
	schema:reviewBody ?body;
	schema:datePublished ?date.
	
	?ProductURI rdf:type schema:Product;
	schema:name ?name;
	schema:category ?category;
	schema:review ?ReviewURI.
  }
  FROM <file:review_sample.csv>
   WHERE {
    BIND (IRI(CONCAT("http://example.org/review/", ?review_id)) AS ?ReviewURI)
	BIND (IRI(CONCAT("http://example.org/product/", ?product_id)) AS ?ProductURI)
	BIND (xsd:string(?product_title) AS ?name)	
	
	BIND (IRI(CONCAT("https://dbpedia.org/resource/", ?marketplace)) AS ?marketplaceCountry)
	BIND (xsd:string(?product_category) AS ?category)
    BIND ((?star_rating) AS ?stars)
	BIND ((?helpful_votes) AS ?votes)
	BIND ((?total_votes) AS ?totalVotes)
	BIND (xsd:string(?review_headline) AS ?headline)
	BIND (xsd:string(?review_body) AS ?body)
	BIND (xsd:date(?review_date) AS ?date)
  }
