@prefix foaf <http://exemple/foaf>
@prefix object <http://exemple/object>


  CONSTRUCT {
  ?URI a ex:Organization;
	ex:name ?NameWithLang;
	ex:CIK ?CIK;
	ex:LEI ?LEI;
	ex:ticker ?Stock_ticker;
  }
  FROM <file:companies.csv>