prefix ex:     <http://example.org/>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix schema: <http://schema.org/>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select ?product ?name ?category (count(?review) as ?count) (avg(?rating) as ?mean_rating)
where {
    ?product schema:review   ?review ;
             schema:name     ?name ;
             schema:category ?category .
    ?review  ex:star_rating  ?rating .
}
group by ?product ?category ?name
order by desc(?count) desc(?mean_rating)
limit 20
